### ISSUE TITLE
Clicking active tab makes tab inactive

### ISSUE THREAD

**Issue by tlvince** [rpocklin/ui-router-tabs#10]
As per #7, I think this is unexpected behaviour as it differs to [ui-bootstrap](https://angular-ui.github.io/bootstrap/#/tabs)'s behaviour; in ui-bootstrap, you cannot click a tab that's already active.

This happens because ui-bootstrap's behaviour is effectively overridden via the use of `ui-sref`.

**Comment by rpocklin** [comment]
Ok, I think the correct behaviour is to disable the `ui-sref` in this case.  Open to a different PR (see comments in PR...)
