### ISSUE TITLE
Upgraded to 1.3.0 and tabs no longer work when clicked

### ISSUE THREAD

**Issue by skidvd** [rpocklin/ui-router-tabs#17]
I recently upgraded from 1.2.0 to 1.3.0 and my tabs stopped working (i.e. I cannot move from the first tab to any other tabs by clicking on them).  No other changes were made in combination with this.  There are no errors/warning/etc. in the console.  Verified that rolling back to 1.2.0 resolved the issue.  

Any ideas what has changed with 1.3.0 that may be causing this?  FYI, I am using angular version 1.4.0.

**Comment by rpocklin** [comment]
There may be a bug with changes in Angular 1.4 I personally haven't tested with it yet since its not released.  Does the example in the repo work with 1.4?

**Comment by skidvd** [comment]
I rolled back to Angular 1.3.14 and the problem still occurs with 1.3.0 but not 1.2.0.  Seems it is not the Angular version.  Have you tested with angular-bootstrap 0.12.1?

**Comment by rpocklin** [comment]
Haven't forgotten this - I will look at it in the next few days.

**Comment by mikalai-sauchanka** [comment]
Fixed by adding '<div ui-view></div>' into DEFAULT_TEMPLATE->tabs->tab. Not sure if it doesn't cause side affects.
Tabs switching worked for me in both 1.2.0 and 1.3.0 versions, but content wasn't displayed

**Comment by rpocklin** [comment]
No, that's definitely not the way to go.

I have tested with angular-bootstrap 0.12.1 and Angular 1.3.14 and it works ok.  Perhaps you can send me a plunkr that fails to diagnose the issue.

**Comment by mikalai-sauchanka** [comment]
Oh, sorry, found the problem - missed <ui-view/> for tab's content. And it's mentioned in the readme... Everything works as expected with Angular 1.3.14.

**Comment by mikalai-sauchanka** [comment]
Well, putting ```<ui-view/>``` near ```<tabs>``` is bad idea, since bootstrap's tabs have well-defined and strict structure which is already generated by angular-ui's tabset. Just look at generated html, and you will understand.

Again, putting ```<ui-view/>``` fixes it. Why do you think it's not the right solution?

**Comment by rpocklin** [comment]
If you want to do that for a custom template, that's ok, but as a plugin developer it's better to give people the option of placing `<ui-view>` anywhere (and within any tag structure) they may want for their app.

**Comment by skidvd** [comment]
I created a simple plunker demonstrating the tab change issue that stops working when upgrading to 1.3.0.  I apologize in advance for how simple it is...

http://plnkr.co/edit/F9jzu3wl89ilPYHoENrV

It defaults to using the 1.2.0 version and tab selections works just fine.  If you modify line 15 of index.html, you can see that they no longer work after upgrade to 1.3.0:

simply replace: `<script src="ui-router-tabs.1.2.0.js"></script>` with:
`<script src="ui-router-tabs.1.3.0.js"></script>`

What am I missing or doing wrong?

**Comment by mikalai-sauchanka** [comment]
Your code uses custom template (detailTabs.html), which has ```ng-click="changeTab(tab)"``` to change active tab, in 1.3.0 you should use ```ng-click="go(tab.route, tab.params, tab.options)"```. 
You can find default template in the sources

**Comment by skidvd** [comment]
Thanks mikalai-sauchanka.  Did I miss documentation of that change somewhere?

**Comment by mikalai-sauchanka** [comment]
Actually, I just use it as you do :) Libraries' author is rpocklin, I believe. Anyway, I haven't found any notice about that change.
