### ISSUE TITLE
Bump angular-ui-bootstrap dependency

### ISSUE THREAD

**Issue by QuentinFchx** [rpocklin/ui-router-tabs#20]
https://github.com/rpocklin/ui-router-tabs/blob/master/bower.json#L25 specifies `^0.11.2`
https://github.com/angular-ui/bootstrap/releases `0.12.1` is the last version

**Comment by rpocklin** [comment]
Sure, I can bump it - is there tab functionality (or bugfixes) that has changed though?  We can't assume everyone is using `0.12.1`.

**Comment by QuentinFchx** [comment]
Considering the [diff](https://github.com/angular-ui/bootstrap/compare/0.11.2...master#diff-9073c3d0209295459ab79e243f181520R28) I don't think there are any issues
I'm using this plugin with 0.12.1 (forced bower resolution) and it works well.

**Comment by rpocklin** [comment]
Landed with 6b2bb76a8390ed7a30f873a0700ec3b899df9c3c - v1.4.1.
