### ISSUE TITLE
Disabled Tab update reflects incorrect tab

### ISSUE THREAD

**Issue by skidvd** [rpocklin/ui-router-tabs#25]
If you click on a tab which has been disabled via the disabled attribute, the tab contents do not update as expected.  However the visual representation of which tab is selected incorrectly changes to the tab which has been disabled.  I have tried this in both the 1.4.2 and 1.4.3 versions with the same result.

**Comment by skidvd** [comment]
Never mind.  I found the problem.  I had not updated my custom template to include the changes you added when you enabled the disabled attribute.  Sorry for the non-issue....

**Comment by rpocklin** [comment]
No worries, I was about to ask for a plunkr to reproduce it :)
