### ISSUE TITLE
Use of tab-heading

### ISSUE THREAD

**Issue by parky128** [rpocklin/ui-router-tabs#31]
Hi, you mention in the guide about using <tab-heading> in a custom template directive to control the tab heading itself. I am unsure how to go about doing this, can you provide an example?

**Comment by rpocklin** [comment]
Sure.  If you look at the source code you'll see it uses `attributes.templateUrl` as a default if it is present.  If you define `templateUrl` as a valid view, it will use that instead.  The default (embedded) template is at the bottom of the directive in `ui-router-tabs.js`.  Start with that and get it working, then modify to suit.

**Comment by tim-lukacik** [comment]
Basically, we have to specify the <tab-heading> element in our custom template right? We can't just make a directive for it and use it with the default template because that element isn't there. Correct?
