### ISSUE TITLE
Multiple tabs with the same state

### ISSUE THREAD

**Issue by MartijnWelker** [rpocklin/ui-router-tabs#32]
Hi,

Is it possible to have the same route state with multiple data sets which share the same state?

ex: /users/edit/id_1 and /users/edit/id_2
id_1 and id_2 are parameters, but with the same state, and both in a different tab.

Kind regards,
Martijn W

**Comment by rpocklin** [comment]
Sure, see the main docs page - just use the param attribute when specifying the tab routes for the menu.  Let me know if your stuck getting it to work.

**Comment by MartijnWelker** [comment]
Thanks for your quick response, I misread the documentation, got it working now :)

Have a nice day,
Martijn W
