### ISSUE TITLE
Required to click on tab twice to get class='active'

### ISSUE THREAD

**Issue by umdstu** [rpocklin/ui-router-tabs#34]
First go around, used this directive, and it appears to be changing the URL when clicking each tab. Unfrotunately the active tab state isn't working. URL Changes after first click, tab becomes active class after second click.

Any ideas?

**Comment by rpocklin** [comment]
Is it happening in the example?  If not can you share your code?

**Comment by rpocklin** [comment]
Did you figure this out?  If so please post an example of your code, otherwise i'll close this issue in 3 days.

**Comment by umdstu** [comment]
I did figure it out. there was a typo which I found only after 4 reviews hah. Sorry for the delay and thanks for following up.

**Comment by rpocklin** [comment]
No worries, happy to help.

**Comment by mokone91** [comment]
Hi
I have same problem, but cannot found any typos
```javascript
vm.tabs = [
      {
        heading: 'accountancy',
        route: 'accountancy'
      },
      {
        heading: 'accountancy.invoices.list',
        route: 'accountancy.invoices.list'
      }
    ];

<tabs data="accountancyCtrl.tabs" type="tabs"/>
        <div class="tab-content">
            <div class="tab-pane active">
                <div ui-view="main"></div>
                <div class="clearfix"></div>
            </div>
        </div>

```

**Comment by rpocklin** [comment]
You can't self-close the tabs tag like that, that's the problem.  Close it explicitly.

**Comment by mokone91** [comment]
I try both options,<tabs /> and </tabs> - works same.
fiexd after I set sub-route to both tabs routes.
