### ISSUE TITLE
Can't have multiple routes highlight same tab

### ISSUE THREAD

**Issue by pduey** [rpocklin/ui-router-tabs#37]
I click a "users" tab and get a list of users. I click on a user to load the edit view, but I would like the "users" tab to remain active.

Perhaps the tabData route value could be an array? If the current $state is any of those, then highlight the corresponding tab.

Another solution could be to allow the tabData route to be an abstract state, and any of the child states would highlight the corresponding tab. When the tab is clicked, go to the first child state.

I haven't tested either of those solutions yet.

**Comment by rpocklin** [comment]
Totally get where you are coming from and yes this is supported behaviour.  If you look at the example, 
http://rp.js.org/ui-router-tabs/example/index.html#/user/settings/one this is what is happening with the 'Settings' tab.  If you like at the source code: https://github.com/rpocklin/ui-router-tabs/blob/master/src/ui-router-tabs.js line 74, `isAncestorOfCurrentRoute` you can see it does not use exact matches.

If you want this behaviour, simply make the child route a descendant of the parent route (which is used for the tabs).

Ie. if the users route is `users` for the users tab and the route for edit is `users.edit` this will work fine as in the example.

**Comment by pduey** [comment]
Thanks for responding. I saw that isAncestorOfCurrentRoute is using includes, and given the name figure it should work. I tried it but just didn't get it to work. I'll keep trying.
