### ISSUE TITLE
How to select the first tab on init?

### ISSUE THREAD

**Issue by alexilyaev** [rpocklin/ui-router-tabs#41]
Hi, I'm trying to make the first tab selected by default when the parent view loads.

Here's my setup:
```js
.state('admin.reports.account', {
    url: '/account',
    controller: 'AccountReportController',
    controllerAs: 'reports',
    template: accountView,
.state('admin.reports.account.groups', {
    url: '/groups',
    template: accountGroupsListView
})
.state('admin.reports.account.meetings', {
    url: '/meetings',
    template: accountMeetingsListView
})
```
```js
this.tabsData = [
    {
        heading: 'Groups',
        route: 'admin.reports.account.groups',
        active: true
    },
    {
        heading: 'Meetings',
        route: 'admin.reports.account.meetings'
    }
];
```

```html
<tabs data="reports.tabsData" type="tabs"></tabs>
```

The tabs themselves work correctly, just that setting `active: true` doesn't do anything.
Checking the source code, this is because `$scope.update_tabs` resets the `active` property based on `$scope.active`, but I want to trigger the selection of that specific tab.

Looking at the underlying ui-tabs docs, this should be possible:
https://angular-ui.github.io/bootstrap/#/tabs

And I didn't understand the first tip in the README, the referenced example does not select the first tab automatically.

**Comment by rpocklin** [comment]
Hi.

There's nothing in the docs for ui-router-tabs for `active`.  The reason people use this directive is that it allows them to use *route-driven tabs* so the best way to get to your solution is *not* to show a tab that is highlighted in the parent route, but in fact route to the tab you want to be active.  This is by design and prevents a confusing UI / experience for the user.

**Comment by alexilyaev** [comment]
Yes, you're right.
I guess I'll just do a `$state.go()` to the first tab route in the parent controller.

**Comment by rpocklin** [comment]
You could do that but will get a flicker, you're best bet is to just directly link to the child route from the previous (normal) angular route.  This way you won't need `$state.go`

**Comment by alexilyaev** [comment]
Yeah, that'll be better :-).
Thanks

**Comment by tiagomsmagalhaes** [comment]
Hi...

I'm trying to do accomplish this feature but, i'm probably missing something out... or i didn't understood quite well in the readme.md file


this is my app.js
```
var manageUsersApp = angular.module('manageUsersApp', ['manageUsersAppTabCtrl',
                                                       'ui.router',
                                                       'ui.bootstrap',
                                                       'ui.router.tabs']);


manageUsersApp.config(['$stateProvider', function($stateProvider) {
	  $stateProvider.state('ManageUsers', {
	    url:'',
	    controller: 'manageUsersAppTabCtrl',
	    templateUrl: 'partials/tabs.jsp',
	   }).state('ManageUsers.search', {
	     url:         '/search',
	     templateUrl: 'partials/searchUser.jsp'
	   }).state('ManageUsers.results', {
	     url:         '/results',
	    templateUrl: 'partials/results.jsp'
	  });
	}]);

```

the first state has the tabs, and they stay in the other routes, but i want to get search when i type ManageUsers

and this is almost identical to your example.html, and the index is the same

```
<div class="inner-wrapper">

	<h1>Manage Users</h1>

	<div class="row">
		<div id="tabs">
			<tabs data="manageUsersAppTabData" type="tabs"></tabs>
		</div>

		<div class="col-md-10">
			<ui-view autoscroll></ui-view>
		</div>
	</div>
</div>
```

i tried abstract states but no work

**Comment by alexilyaev** [comment]
What do you mean "when i type ManageUsers"? Where do you type it?
Can you make a small Plunker with you test case?

**Comment by tiagomsmagalhaes** [comment]
i have a ManageUsers.jsp, which is my main file, then i have a partial that loads the tabs, and within that it should load the search view and the results

so i have
```
ManageUsers.jsp - just the header and the tabs
ManageUsers.jsp#/search - with the search form
ManageUsers.jsp#/results - the results table
```
what i want is to enter the first url and display the second url

**Comment by rpocklin** [comment]
This isn't how routing typically works but you have other options.  add a `state.go (...)`in that first routes controller will do it, or simply link to that second route directly.

**Comment by tiagomsmagalhaes** [comment]
what do you mean? i just adapted your example to have a horizontal navigation tabs

**Comment by alexilyaev** [comment]
In my case I had a top navigation to the initial parent route, so I just updated the nav `ui-sref`.
In your case, it's your top route, so you'll have to use `$state.go()` in your controller to the `ManageUsers.search` state.
