### ISSUE TITLE
Bump version on NPM

### ISSUE THREAD

**Issue by alexilyaev** [rpocklin/ui-router-tabs#42]
Can we bump the version on NPM? I see it's `1.4.2` there:
https://www.npmjs.com/package/angular-ui-router-tabs

**Comment by rpocklin** [comment]
Wow.. it's missed a few releases hey :)

Published `1.5.1` just now.

**Comment by alexilyaev** [comment]
Cool.

Also, for some reason, the repo link there is for `npm` and not this project.
