### ISSUE TITLE
Add commonjs package manager support

### ISSUE THREAD

**Issue by alexilyaev** [rpocklin/ui-router-tabs#43]
Can we add support for loading uiRouterTabs as a CommonJS module?

See example of Angular UI-Router:
https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js

This will allow doing:
```js
var uiRouterTabs = require('angular-ui-router-tabs');

angular.module('admin', [
    uiRouterTabs
])
```

Instead of hard coding the module name.

**Comment by rpocklin** [comment]
Happy to accept a PR - can I ask for curiosity why you use it this way, and are many other directives starting to support this as a standard?

**Comment by alexilyaev** [comment]
Preparing a PR.

e.g. I'm using WebPack with ES6, looks something like this:
```js
import uiRouter from 'angular-ui-router';

angular.module('app', [
    uiRouter
]);
```

It's just one less thing to think about when loading dependencies.
And one less instruction to add in the project README.

All Angular modules support this, and other projects started to adopt it as well.
e.g.
```js
import jsDataAngular from 'js-data-angular';
```
