### ISSUE TITLE
new version of ui.bootstrap is out

### ISSUE THREAD

**Issue by hackzilla** [rpocklin/ui-router-tabs#45]
Would it not make sense to relax the dependancy of ```ui.bootstrap```?

Something like:

```
    "angular-bootstrap": "~0.13",
```

**Comment by rpocklin** [comment]
Do you have a specific reason?  ^ seems to be the new accepted way.

**Comment by hackzilla** [comment]
only reason was I was following a guide and 0.14.1 was the dependancy.

I've noticed that ^ is the accepted way, but after reading about it, the affect is different if you are <1.0

I've dropped my requirement down 0.13 so there is no rush.

**Comment by rpocklin** [comment]
I will release a new version for 0.14 in the next week - there are some changes to merge first.
