### ISSUE TITLE
Example link not working

### ISSUE THREAD

**Issue by edriang** [rpocklin/ui-router-tabs#48]
Some resources gives 404 not found at http://rp.js.org/ui-router-tabs/example/index.html

index.html:7 GET http://rp.js.org/ui-router-tabs/bower_components/bootstrap/dist/css/bootstrap.css 
index.html:16 GET http://rp.js.org/ui-router-tabs/bower_components/jquery/dist/jquery.js 
index.html:19 GET http://rp.js.org/ui-router-tabs/bower_components/angular-bootstrap/ui-bootstrap-tpls.js 
index.html:18 GET http://rp.js.org/ui-router-tabs/bower_components/bootstrap/dist/js/bootstrap.js 
index.html:17 GET http://rp.js.org/ui-router-tabs/bower_components/angular/angular.js 
index.html:20 GET http://rp.js.org/ui-router-tabs/bower_components/angular-ui-router/release/angular-ui-router.js

**Comment by rpocklin** [comment]
Thanks, fixed.
