### ISSUE TITLE
disabled not working

### ISSUE THREAD

**Issue by ArielCabib** [rpocklin/ui-router-tabs#49]
I looked it and there's a conflict between the code and the docs.
In the docs the key for disabling is 'disabled' and in the code it's 'disable'.
The fix is 5 minutes, I'm willing to fix it and create a PR. Just need to know which one should it be, disable or disabled.

**Comment by rpocklin** [comment]
Sorry, was quicker for me to just update it.  Thanks, let me know if there's anywhere else that's missed it.
