### ISSUE TITLE
Can't access the options defined in tabData in either controller or ui router

### ISSUE THREAD

**Issue by tuxysuse** [rpocklin/ui-router-tabs#57]
First of all thank you for creating UI Router tabs library. It is very helpful and I am using for a sample project while learning Angular JS.
I am trying to use the options parameter in tabData as mentioned in the Readme.md like below:
 {
      heading: 'Accounts',
      route:   'user.accounts',
      params:  {
                 accountId: account.id
               },
     options: {}
    }
I am passing custom data in this options parameter and same I want to use in the respective controller. But I am not successful to access the parameters either in the ui router or controller. I am able to access the params in router and passing it to the controller using resolve parameter.
I followed the same resolve parameter in ui router for the options parameter also, but with no luck.
I would like to inject into the data parameter of ui router so that I can access with $state.current.data.myVariable (or) is there any way to access in the controller with selected tab options.

**Comment by rpocklin** [comment]
If you could provide a plunkr I can play with that will help?  If you can give an explicit example of how you want to use the options or params that may help as well.

**Comment by rpocklin** [comment]
Will close soon if no response.
