### ISSUE TITLE
Breaking change planned to tab API in UI Bootstrap

### ISSUE THREAD

**Issue by wesleycho** [rpocklin/ui-router-tabs#58]
Hey, giving advance notice, a breaking change is (likely) coming in UI Bootstrap 1.2 for the tab component, where the tab API is changing in a major way. See https://github.com/angular-ui/bootstrap/pull/5425 for the usage difference.

**Comment by rpocklin** [comment]
Thanks for the heads up :)

**Comment by rpocklin** [comment]
I'm getting to this now, thanks.
