### ISSUE TITLE
Ability to 'properly' have <ui-view></ui-view> inside tab-content

### ISSUE THREAD

**Issue by immortalcy** [rpocklin/ui-router-tabs#59]
Following issue #24 is there a way (custom template maybe) to have the `<div class="tab-content"></div>` be filled automatically by defining a <ui-view> inside ??

examples like:

```
<div class="row">
      <div class="col-md-12">
        <div class="tab-container">
          <tabs data="tabData" type="tabs"></tabs>
          <div class="tab-content">
            <div ui-view></div>
          </div>
        </div>
      </div>
    </div>
```

wouldn't do anything. I wouldn't want to hide the tab content since it is already there by the template.

**Comment by rpocklin** [comment]
Not sure I get what you mean, the example `example/example.html` does almost this exact thing.
I would like to understand what you are trying to achieve?  Perhaps a plunkr would help.

You can certainly override the default template by doing:
`$templateCache.put('ui-router-tabs-default-template.html', CUSTOM_TEMPLATE);`

**Comment by mareczek** [comment]
there is a pull request for that (https://github.com/rpocklin/ui-router-tabs/pull/60)

**Comment by immortalcy** [comment]
Great, thank you... haven't had time to play around lately. I can see that the request is not merged yet. would be great to have it on a next release!!

**Comment by rpocklin** [comment]
Made similar changes to `master` branch, feel free to give feedback on it.
