### ISSUE TITLE
Double initialisation of child state controller

### ISSUE THREAD

**Issue by mareczek** [rpocklin/ui-router-tabs#61]
Hi there!

I configured the two child states in the router passing the name of the controller. When the view loads on the page with tabs the controller is initialised twice. Did you also encounter this behaviour?

Thanks

**Comment by rpocklin** [comment]
Can you please create a plunkr that reproduces this?

**Comment by mareczek** [comment]
false alarm, it's because of the ui-view being present multiple times (on each tab content)
