### ISSUE TITLE
Tab heading Icon

### ISSUE THREAD

**Issue by sajumani** [rpocklin/ui-router-tabs#64]
Hi

  How do we add heading icon with tab data...???

$scope.tabData   = [
      {
        heading: "Settings <i>fdf</i>",
        route:   'user.settings'
      },
      {
        heading: 'Accounts',
        route:   'user.accounts'
      }
    ];

**Comment by rpocklin** [comment]
It's a feature request.  You might be able to do something with `:before` or `:after` elements but it's in the pipeline.

**Comment by fireole** [comment]
was this feature added by chance?   thanks

**Comment by sajumani** [comment]
thanks for your reply,... but i edited your directive template and it works fine

**Comment by rpocklin** [comment]
Yes it's been added now, am working to finalise a new version release and update the docs.
