### ISSUE TITLE
Does not work when template is in templateCache

### ISSUE THREAD

**Issue by CarbonFactory** [rpocklin/ui-router-tabs#68]
If I put the template in a cache.js file, clicking on the tabs does nothing

`<div class="wrapper-md" ng-controller="AdminController as scope">
	<div class="row">
	  <div class="col-md-12">
		<tabs data="scope.tabData" type="tabs" />
		<div ui-view="tabs"></div>
	  </div>
	</div>
</div>`

The same when referred to in the ui-router's templateUrl with the full path of the html then it works, but not when the templateUrl contains the templateCache's key

**Comment by rpocklin** [comment]
First time this has been mentioned - can you supply a plunkr?

**Comment by CarbonFactory** [comment]
[Plunkr](http://plnkr.co/edit/hDboBqu0ZUN2GTUhs20r)

`  
.state('admin', {
            abstract: true,
            url: '/admin'
          })
          .state('admin.data', {
            url: '/data',
            views: {
              'index@': {
                templateUrl: 'templates/adminData.html'
              }
            }
          })
          .state('admin.data.grades', {
            url: '/grades',
            views: {
              'tabs@admin.data': {
                templateUrl: 'templates/grades.html'
              }
            }
          })
`
When I load the `adminData` via templateCache, clicking on the child tabs does not load the child state. But, if I load the `adminData` by referencing the html file, it works

**Comment by rpocklin** [comment]
Why couldn't you just pass in `templateUrl` for this?  That plunkr has way too much going on.

**Comment by CarbonFactory** [comment]
you mean to pass the full path of the file ? the way I'm doing as of **_now?_**
