### ISSUE TITLE
Tab for current route not set to active using Bootstrap.UI 1.2.4

### ISSUE THREAD

**Issue by mjbeswick** [rpocklin/ui-router-tabs#70]
The latest version of Bootstrap.UI 1.2.4 breaks the functionality setting the tab matching the current route. Works with previous version Bootstrap.UI 1.2.

I have stepped though the ui-router-tabs.js, and isAncestorOfCurrentRoute is being set to true for the correct tab, although when the page finishes loading, the first tab is always set to active.

**Comment by rpocklin** [comment]
Yep, looks like there's a bit of work to do with this new version of Bootstrap.UI.

**Comment by ulejon** [comment]
Having the same issue. Any idea when this can be fixed?

**Comment by ulejon** [comment]
We are using bootstrap ui 1.2.2

**Comment by primavera133** [comment]
I have the same issue with Bootstrap UI 1.2.2. It seems Bootstrap UI moved the active-attribute to the uib-tabset element, and the value of it should be the active tab index.

**Comment by primavera133** [comment]
Close to presenting a fix now but it breaks the tests for $stateChangeStart cancel that still routes. Cannot see why my code would break that, so it's probably something with the UI-update. No more time to spend on it at the moment, though... :/
[ui-router-tabs.js.zip](https://github.com/rpocklin/ui-router-tabs/files/182467/ui-router-tabs.js.zip)

**Comment by rpocklin** [comment]
Can't do much with a zip, presenting a branch from your repo (forked from this) would have been a better way to go.

**Comment by primavera133** [comment]
Yeah, sorry about that. Will see if I can get some time to do this better.

**Comment by rpocklin** [comment]
Please test out using the master branch, if it's all good I will release it.

**Comment by dcheney** [comment]
Same issue with Bootstrap 1.1.2.

As Bootstrap UI moved the active-attribute to the uib-tabset element, a patch that works for me is:
==
        $scope.update_tabs = function() {
          // sets which tab is active (used for highlighting)
          angular.forEach($scope.tabs, function(tab, index) {       // include index
            tab.params = tab.params || {};
            tab.options = tab.options || {};
            tab.active = $scope.active(tab);
            if ($scope.active(tab)) { $scope.tabs.active = index; }
          });
        };
==
and use 'active=tabs.active' in the template:
==  
    var DEFAULT_TEMPLATE = '<div><uib-tabset class="tab-container" type="{{type}}" vertical="{{vertical}}" active=tabs.active ' +
      'justified="{{justified}}">' + '<uib-tab class="tab" ng-repeat="tab in tabs" heading="{{tab.heading}}" ' +
      'active="tab.active" disable="tab.disable" ng-click="go(tab)">' +
      '</uib-tab></uib-tabset></div>';
==

**Comment by rpocklin** [comment]
Thanks for the suggestion, am working to release a new version this week.

**Comment by rpocklin** [comment]
Released v2.0.0, feel free to raise any issues against it.
