### ISSUE TITLE
Update dependencies on bower.json file

### ISSUE THREAD

**Issue by immortalcy** [rpocklin/ui-router-tabs#72]
Regarding this github [https://github.com/angular-ui/bootstrap-bower/issues/70#issuecomment-215059084](issue) could you please update bower file if this doesn't have any conflicts?

I can confirm that when I manually copied `angular-bootstrap` v1.3.2 files everything worked perfectly. **Please note that I didn't make any thorough checks**.

**Comment by rpocklin** [comment]
Thanks for the feedback, he just needs to fix his version since this repo is moving forward to v14 and the world has changed around him :P
