### ISSUE TITLE
update to latest version on npm as well - active tab not set properly when url loaded

### ISSUE THREAD

**Issue by aks0020** [rpocklin/ui-router-tabs#73]
npm version still using very old version, please update.
https://www.npmjs.com/package/angular-ui-router-tabs

**Comment by aks0020** [comment]
@rpocklin  Active tab not still not selected with UI Bootstrap 1.3.2 - `active` (index) attribute has been moved to `<uib-tabset>`

Also tab child controllers are loaded two times on page load can anyone suggest why it is loaded twice?

**Comment by rpocklin** [comment]
If you read the current PRs and issues we are about to release a new version to support UI Bootstrap 1.x.x so please hold off on those related issues until it has been released.

**Comment by aks0020** [comment]
ok btw that two times ctrl load issue is not occurring if I use custom template & specify `<ui-view></ui-view>` in parent.
Currently I have fixed active tab issue in my local copy by moving active attrib. to `<uib-tabset>`.
Also please release latest version to npm after you add support for  latest UI Bootstrap(1.3.x) so I can switch again to npm version. Thanks.

**Comment by rpocklin** [comment]
No worries, those issues have been addressed in the new version, should be released this week.

**Comment by rpocklin** [comment]
Released v2.0.0, feel free to raise any issues against it.
