### ISSUE TITLE
How to prevent reloading after changing the tab

### ISSUE THREAD

**Issue by zhanghuanchong** [rpocklin/ui-router-tabs#77]
The tab will reload after changing to other tab and come back. How to prevent this?

**Comment by rpocklin** [comment]
What do you expect to happen?  Nothing is storing transient state anywhere, UI Router doesn't work like this (out of the box).  If you want to save state between routes i'd recommend the ui-router-extras package or use local storage to cache / restore transient view state.  This library isn't doing anything special WRT to this.

**Comment by zhanghuanchong** [comment]
Thank you. I have managed to prevent reloading with [ui-router-extras](https://github.com/christopherthielen/ui-router-extras). 👍 

"Sticky State" and "Deep State Redirect" work for me. 😆
