### ISSUE TITLE
Properly annotate functions for dependency injection

### ISSUE THREAD

**Issue by phw** [rpocklin/ui-router-tabs#8]
It would be great if ui-router-tabs would properly annotate all functions were dependency injection is used. Without proper annotation code minification will break Angulars dependency injection, see https://docs.angularjs.org/tutorial/step_05#a-note-on-minification

I know this can be done afterwards with tools like ng-annotate, but especially for code that is included as an external library proper annotations are preferred.

**Comment by rpocklin** [comment]
Couldn't agree more.  It was done in v1.1.4 but I noticed the tag wasn't pushed so you wouldn't see this via `bower install` or update.  Please update to the latest version and you'll find it done.

**Comment by phw** [comment]
Thanks for the fast fix, works as expected :)
