### ISSUE TITLE
How to prevent page refresh while tab changes ?

### ISSUE THREAD

**Issue by fireworkstudio** [rpocklin/ui-router-tabs#84]
How to prevent page refresh while tab changes ? Thanks.

**Comment by pkishino** [comment]
can you show a plunker that shows that behaviour please? I am not quite sure what you mean by refresh, if you mean full page refresh then that should not be happening.
which versions are you using etc?

**Comment by fireworkstudio** [comment]
@pziegler 

Take this example: I have two tabs: tabA and tabB, both contain some text input and datatable component. First fill some data in tabA and then press tabA's search button, tabA's datatable will present data sent from server. Then switch to tabB and return to tabA. The data in text input and datatable disappeared as the tabA's controller reinitialized.

I tried some methods , such as 
$state.transitionTo(tab.route, tab.params, { reload: false, inherit: false, notify: true });

but still not resolved. 
BTW, I am using AngularJS 1.3.9, UI-Router 0.2.18

Thanks

**Comment by pkishino** [comment]
should merge this question with #82 
it's about keeping the content and stateful transitions as well.
would be better to keep discussion in one thread.
found this in ui-router 
https://github.com/angular-ui/ui-router/issues/2096
I would look on stackexchange or the ui-router project as this isnt really related to the tabs project itself

**Comment by fireworkstudio** [comment]
@pziegler 

I think it's issue of ui-router project,  should I close current issue ?

**Comment by pkishino** [comment]
yes, I think that would be preferable . You can always link to this issue when you create a new issue there (or if you search you might find..) I think you want something like sticky states or so

**Comment by fireworkstudio** [comment]
@pziegler 
Thanks, I am closing this issue

**Comment by softzer0** [comment]
Seems like that behavior has been fixed in the latest update of `ui-router` for Angular 1, but if I'm not wrong that is still not yet released - current revision is still in development state (the latest version is still 0.3.1)...

**Comment by fireworkstudio** [comment]
@MikiSoft 
That's cool, looking forward to it

**Comment by softzer0** [comment]
I forgot to ask, have you tried it on v0.3.1 to see if it works with it?

**Comment by fireworkstudio** [comment]
@MikiSoft 
I used another open source solution which depends on tabs. 
[sx-tabs](https://github.com/shaunxu/angular-toolkits/tree/master/tabs)

Here is my demo project (not completed yet)
[firework-admin](https://github.com/fireworkstudio/firework-admin)

and this is one screenshot
![image](https://camo.githubusercontent.com/ecfc8f532f6c488232d2dc947f151d431ff7fa5a/687474703a2f2f37786b6e72382e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f61737365742f7265736f757263652f32303136313030383030323233312e6a70673f696d61676556696577322f322f772f383030)
