### ISSUE TITLE
Tabs stacked up with screen is narrow

### ISSUE THREAD

**Issue by RonAlmog** [rpocklin/ui-router-tabs#85]
The tabs works great for me, but one little problem: when the screen width gets below 960px (bootstrap large), the tabs become stacked one above the other. and I don't want that. i have plenty of room even in sm or xs sizes for the full 3 tabs. 
How can I avoid the stacking?
Or: How can i get a different behavior (or different class of tabs) for different screen widths?

**Comment by rpocklin** [comment]
The example has a `col-md-2` on the tabs - if you change this to `col-md-12` it will stay across the screen rather than stacking.  If you have more problems, please create a plunkr and i'll take a look.

**Comment by RonAlmog** [comment]
You're right. 
No, i had the class as col-md-12 all the time, but my mistake was to think that the stacking is caused by the directive, and after your answer i looked closer and saw it is actually our code ('responsive css') that does that. then fixed easily. thank you!
